server:
  port: 8085

spring:
  application:
    # ĐÂY LÀ DÒNG BẮT BUỘC: Đặt tên để Eureka và Gateway nhận diện
    name: service-salary
eureka:
  client:
    service-url:
      # LƯU Ý: Nếu chạy bằng Docker, phải dùng tên container là "eureka-server"
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true