# 1. C?u hình c?ng ch?y Service (Vì là Microservice nên tránh c?ng 8080 n?u Auth ?ã dùng)
server.port=8081

# 2. C?u hình k?t n?i SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ServicePOS;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 3. C?u hình Hibernate (T? ??ng t?o b?ng t? Entity)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Gi? nguyên tên b?ng và c?t y h?t nh? mình ??t trong code Java (không t? d?ch sang g?ch d??i)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl