server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    # Vì đây là Server, nó không cần tự đăng ký chính nó
    register-with-eureka: false
    # Nó cũng không cần đi lấy danh sách từ server khác (trừ khi chạy Cluster)
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  server:
    # Tắt chế độ "Tự bảo vệ" để tránh dòng chữ EMERGENCY màu đỏ khi Dev
    enable-self-preservation: false
    # Thời gian quét để gỡ bỏ các service đã "chết" (tính bằng ms)
    eviction-interval-timer-in-ms: 5000