server.port=8086
spring.datasource.url=jdbc:sqlserver://sqlserver:1433;databaseName=ServiceUser;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true;serverTimezone=Asia/Ho_Chi_Minh
spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.datasource.username=sa
spring.datasource.password=CafePos@123456
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

logging.level.org.springframework.security=DEBUG
# Tự động tạo/cập nhật bảng (chỉ dùng khi phát triển)
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=guimaotp@gmail.com
spring.mail.password=dypr fmms xmup vgwd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true